=== Creating PreAuthExecutor (Command-Executor)

After initiating the order details, next we will be creating an executor called `PreAuthExecutor`.
It is responsible for making `PreAuth` by calling to the utility `payment-service`.
Due to the execution should be reverted if the LRT is not successful as wished, the `PreAuthExecutor` is implemented from the `CommandExecutor` interface.

To make the PreAuth request, we should provide the `userId`, `amount` and `orderId`.
And to revert the process we have to provide the `PreAuthRef` back.

[source,java]
----
// <1>
@SagaExecutor(executeFor = "payment-service", value = "PreAuthExecutor")
@RequiredArgsConstructor
public class PreAuthExecutor implements CommandExecutor<PlaceOrderAggregator> { // <2>

    private final PaymentService paymentService; //<3>

    @Override
    public ProcessStepManager<PlaceOrderAggregator> doProcess(
            PlaceOrderAggregator currentAggregator,
            ProcessStepManagerUtil<PlaceOrderAggregator> stepManager,
            String idempotencyKey
    ) throws RetryableExecutorException, NonRetryableExecutorException {
        //<4>
        currentAggregator.getExecutions().add(this.getClass().getSimpleName()+":"+ LocalDateTime.now());
        //<5>
        final String preAuthRef = this.paymentService.makePreAuth(
                PreAuthDto
                        .RequestBody
                        .builder()
                        .userId(currentAggregator.getUserId())
                        .amount(currentAggregator.getAmount())
                        .orderId(currentAggregator.getAggregatorTransactionId())
                        .build()
        );
        // <6>
        currentAggregator.setPreAuthRef(preAuthRef);
        // <7>
        return stepManager.next(StockUpdateExecutor.class, OrderStatus.MADE_PRE_AUTH);
    }

    @Override
    public SagaExecutionEventName doRevert(
            NonRetryableExecutorException processException,
            PlaceOrderAggregator finalAggregatorState,
            RevertHintStore revertHintStore
    )
    throws RetryableExecutorException {

        this.paymentService.releasePreAuth(
                PreAuthReleaseDto.RequestBody.builder()
                        // <8>
                        .pareAuthRef(finalAggregatorState.getPreAuthRef())
                        // <9>
                        .reason(processException.get("reason").orElse(""))
                        .build()
        );
        revertHintStore.put(
                String.valueOf(System.currentTimeMillis()),
                this.getClass().getSimpleName() + ":doRevert"
        );// <10>

        return OrderStatus.RELEASED_PRE_AUTH; // <11>
    }
}
----

<1> Annotate the `PreAuthExecutor` class as a `SagaExecutor` by using `@SagaExecutor` annotation.
+
*executeFor*:: executeFor is the target serviceâ€™s name.
*value*:: value is the bean name of the executor.

<2> Implement the `PreAuthExecutor` from the `CommandExecutor` by passing the target Aggregator due to preAuth atomic execution has a compensation process.

<3> Autowire xref:stacksaga-demo.adoc#creating_payment_service[PaymentService Class] to make the request to payment-service.

<4> Adding the current executor to the Executions list to keep track via the StackSaga Cloud-Window.
(This part is only for logging purposes to understand).

<5> make the pre-auth process by invoking the PaymentService's `makePreAuth()` method. all the required data (userId, amount, orderId) that should be passed to pre-auth is in the aggregator object, and it can be accessed here to pass.

<6> Update the `currentAggregator` with `preAuthRef` data that received as the response.
It will be used in the make-payment executor.

<7> Navigates the execution by using `stepManager` to the next executor called `StockUpdateExecutor`.
And also passed the status as `MADE_PRE_AUTH`.


<8> For Calling the PaymentService's `releasePreAuth()` we have to provide the `pareAuthRef` data.
So we have the last aggregator data that was updated until the end of the process to forward.
Therefore, that contains the `pareAuthRef` and we can access it from the `finalAggregatorState`.

<9> And As well as a reason should be given for the releasing `PreAuth`.
All the time the process can be failed (With  `NonRetryableExecutorException`)we have added a data called `reason` with the `NonRetryableExecutorException`.
This is the time that can be used.

<10> Update the hint-store object by adding current millisecond and the revert method name with the executor name while the revert process.  +
In your real application, xref://[the hint-store] can be used for adding some data regarding the revert process.
It can be accessed from the next revert process.


<11> Return the status as `RELEASED_PRE_AUTH`  finally.

[[creating_payment_service]]
=== Creating PaymentService

`PaymentService` is a regular spring service that creates for calling utility `payment-service`.
Due to the `payment-service` is another utility service we have to call it through http or any other protocol that target service supports (Most probably API endpoints are exposed by http protocol).
This example's `payment-service` also support http endpoint to access the API.
Therefore, we will be using rest template as http client.
But you can use any Http client like Feign-client, Okhttp, Spring-webclient and so on.

[source,java]
----
@Service
@RequiredArgsConstructor
public class PaymentService {

    private final RestTemplate restTemplate;

    public String makePreAuth(PreAuthDto.RequestBody requestBody)
        throws RetryableExecutorException, NonRetryableExecutorException { // <1>

        try {
            // <2>
            PreAuthDto.ResponseBody responseBody = this.restTemplate.postForObject(
                    "http://payment-service/pre-auth",
                    requestBody,
                    PreAuthDto.ResponseBody.class
            );
            assert responseBody != null;
            // <3>
            return responseBody.getPreAuthRef();
        } catch (HttpClientErrorException ex) { // <4>
            // This exception is thrown for HTTP 4xx errors (Client errors)
            // You can handle specific HTTP error codes here
            if (ex.getStatusCode().equals(HttpStatus.FORBIDDEN)) {
                // <5>
                throw NonRetryableExecutorException
                        .buildWith(
                                new InsufficientBalanceException("Balance not sufficient"),
                                ""
                        )
                        .build();
            } else {
                // <6>
                throw NonRetryableExecutorException.buildWith(ex, "").build();
            }
        } catch (HttpServerErrorException ex) {  // <7>
            // This exception is thrown for HTTP 5xx errors (Server errors)
            // You can handle specific HTTP error codes here
            if (ex.getStatusCode().equals(HttpStatus.INTERNAL_SERVER_ERROR)) {
                // <8>
                throw NonRetryableExecutorException.buildWith(ex, "").build();
            } else {
                //502 , 503, 504, 509 etc.
                // <9>
                throw RetryableExecutorException.buildWith(ex).build();
            }
        } catch (RestClientException ex) {  // <10>
            // This exception is a generic RestClientException
            // Handle other types of exceptions here
            // <11>
            throw ex;
        } catch (IllegalArgumentException illegalArgumentException) {
            throw RetryableExecutorException.buildWith(illegalArgumentException).build();
        }

    }

    public void releasePreAuth(PreAuthReleaseDto.RequestBody requestBody) throws RetryableExecutorException {
        try {
            // <12>
            this.restTemplate.put(
                    "http://payment-service/pre-auth/release",
                    requestBody
            );
        } catch (HttpServerErrorException ex) {// <13>
            // This exception is thrown for HTTP 5xx errors (Server errors)
            // You can handle specific HTTP error codes here
            if (ex.getStatusCode().equals(HttpStatus.INTERNAL_SERVER_ERROR)) {
                // <14>
                throw NonRetryableExecutorException.buildWith(ex, "").build();
            } else {
                //502 , 503, 504, 509 etc.
                // <15>
                throw RetryableExecutorException.buildWith(ex).build();
            }
        } catch (RestClientException ex) { // <16>
            // This exception is thrown for HTTP 4xx errors (Client errors)
            // You can handle specific HTTP error codes here
            // <17>
            throw ex;
        } catch (IllegalArgumentException illegalArgumentException) {
            throw RetryableExecutorException.buildWith(illegalArgumentException).build();
        } catch (RuntimeException restOfExceptions) { // <18>
            log.error("Unhanded exception : {}", restOfExceptions.getMessage());
            log.warn("Unhanded exception was occurred and ignored while releasing pre-auth: {}", restOfExceptions.getMessage());
        }
    }
}
----

<1> We have thrown both `NonRetryableExecutorException`,and `RetryableExecutorException` that PreAuthExecutor's `doPrcess()` method expects.
The handling exception part is done in the service layer.
+
[ Read the xref:creating-UserDetailExecutor.adoc#exception_tip[TIP] ]

<2> Call the http request to the utility payment-service.

<3> Returns the `authRef` that received as the response to the `PreAuthExecutor`.

<4> Catch the https://en.wikipedia.org/wiki/List_of_HTTP_status_codes[*4xx*] HTTP errors to determine if the exception is a `NonRetryableExecutorException` or `RetryableExecutorException`.

<5> An error can be thrown by the payment-service when we try to make a pre-auth if the user has no enough balance for making the pre-auth.
Therefore, the `FORBIDDEN` error code is filtered and throws it as `NonRetryableExecutorException` wrapping with a new exception called `InsufficientBalanceException`.

<6> Other 4xx errors are thrown as `NonRetryableExecutorException`.

<7> Catch the https://en.wikipedia.org/wiki/List_of_HTTP_status_codes[*5xx*] HTTP errors to determine if the exception is a `NonRetryableExecutorException` or `RetryableExecutorException`.
Most probably 5xx errors can be retried, but there are some cases it can not.

<8> Check the 5xx error is equal to `INTERNAL_SERVER_ERROR`.
Because if there is an internal server in this case, we know that we cannot go ahead and the process should be stopped going forward.
Therefore, `NonRetryableExecutorException` is thrown by wrapping the real letter.

<9> If the 5xx is not equal to `INTERNAL_SERVER_ERROR`, then other errors like 502, 503, 504, 509 error codes are caught as `RetryableExecutorException` and therefore a `RetryableExecutorException` is thrown by wrapping the real exception.

<10> Catch the other exceptions.

<11> In this example, other error codes are not considered because we assume that errors cannot be happened.
Therefore, that error just throws without wrapping with `NonRetryableExecutorException`.
IF you want to wrap, you can do as usual but is not required if you don't consider those errors.
Because internally the framework wraps the all `RuntimeExceptions` with `NonRetryableExecutorException` by default.

<12> Making the request to the utility payment-service to release the PreAuth that we made.
This method is the Compensating of the `makePreAuth`.

<13> Catch the https://en.wikipedia.org/wiki/List_of_HTTP_status_codes[*5xx*] HTTP errors to determine if the exception is a `NonRetryableExecutorException` or `RetryableExecutorException`.
Most probably 5xx errors can be retried, but there are some cases it can not.


<14> If the 5xx is not equal to `INTERNAL_SERVER_ERROR`, then other errors like 502, 503, 504, 509 error codes are caught as `RetryableExecutorException` and therefore a `RetryableExecutorException` is thrown by wrapping the real exception.



<15> If the 5xx is not equal to `INTERNAL_SERVER_ERROR`, then other errors like 502, 503, 504, 509 error codes are caught as `RetryableExecutorException` and therefore a `RetryableExecutorException` is thrown by wrapping the real exception.



<16> Catch the other exceptions.

<17> In this example, other error codes are not considered because we assume that errors cannot be happened.
Therefore, that error just throws without wrapping with `NonRetryableExecutorException`.
IF you want to wrap, you can do as usual but is not required if you don't consider those errors.
Because internally the framework wraps the all `RuntimeExceptions` with `NonRetryableExecutorException` by default.

<18> Ignore other all unknown (Unhandled) exceptions to avoid the transaction termination.

[[tip_for_avoid_transaction_termination]]
TIP: If you think that, even if the revert execution is failed for some reason (due to an unhandled exception,) the rest of revert executions should be run without terminating the transaction, you can flow this.

